import {
  LayoutDashboard, Building2, Users, Wifi, Cpu, FileCode2,
  Smile, Package, Database, History, Bell, Link2,
  AlarmClock, UserCheck, Timer, CalendarClock,
  Palette, Settings, BarChart3, Activity, Zap,
  CreditCard, ShoppingBag, Calendar, Layers, Clock,
  BellRing, BrainCircuit, Gauge, TrendingUp, AlertOctagon,
  LayoutTemplate, ShieldCheck, Boxes,
} from 'lucide-react'

export const adminNav = [
  { divider: true, label: 'Main' },
  { to: '/admin',               label: 'Dashboard',        icon: LayoutDashboard },
  { to: '/admin/custom-dashboard', label: 'Custom Dashboards', icon: LayoutTemplate },
  { divider: true, label: 'Management' },
  { to: '/admin/organizations', label: 'Organizations',    icon: Building2 },
  { to: '/admin/users',         label: 'Users',            icon: Users },
  { to: '/admin/gateways',      label: 'Manage Gateway',   icon: Wifi },
  { to: '/admin/devices',       label: 'Devices',          icon: Cpu },
  { to: '/admin/device-templates', label: 'Device Templates', icon: FileCode2 },
  { to: '/admin/access-groups', label: 'Access Groups',    icon: ShieldCheck },
  { to: '/admin/device-groups', label: 'Device Groups',    icon: Boxes },
  { to: '/admin/icons',         label: 'Manage Icons',     icon: Smile },
  { to: '/admin/products',      label: 'Manage Products',  icon: Package },
  { divider: true, label: 'Data' },
  { to: '/admin/data-center',   label: 'Data Center',      icon: Database },
  { to: '/admin/historical-data', label: 'Historical Data',icon: History },
  { to: '/admin/variable-alarms', label: 'Variable Alarms',icon: Activity },
  { to: '/admin/linkage-records', label: 'Linkage Records',icon: Link2 },
  { divider: true, label: 'Alarms' },
  { to: '/admin/template-triggers', label: 'Template Triggers', icon: Bell },
  { to: '/admin/alarm-settings',    label: 'Alarm Settings',    icon: AlarmClock },
  { to: '/admin/alarm-contacts',    label: 'Alarm Contacts',    icon: UserCheck },
  { divider: true, label: 'System' },
  { to: '/admin/device-timestamps', label: 'Device Timestamps', icon: Timer },
  { to: '/admin/schedule-tasks',    label: 'Schedule Tasks',    icon: CalendarClock },
  { to: '/admin/theme-settings',    label: 'Theme Settings',    icon: Palette },
  { to: '/admin/settings',          label: 'Settings',          icon: Settings },
]

export const orgNav = [
  { divider: true, label: 'Main' },
  { to: '/org',                    label: 'Dashboard',       icon: LayoutDashboard },
  { to: '/org/custom-dashboard',   label: 'Custom Dashboards', icon: LayoutTemplate },
  { divider: true, label: 'Devices' },
  { to: '/org/devices',            label: 'My Devices',      icon: Cpu },
  { to: '/org/access-groups',      label: 'Access Groups',   icon: ShieldCheck },
  { to: '/org/device-groups',      label: 'Device Groups',   icon: Boxes },
  { to: '/org/gateways',           label: 'Gateways',        icon: Wifi },
  { to: '/org/device-templates',   label: 'Device Templates',icon: FileCode2 },
  { divider: true, label: 'Data' },
  { to: '/org/historical-data',    label: 'Historical Data', icon: History },
  { divider: true, label: 'Alarms' },
  { to: '/org/template-triggers',  label: 'Template Triggers', icon: Bell },
  { to: '/org/alarm-settings',     label: 'Alarm Settings',    icon: AlarmClock },
  { to: '/org/alarm-contacts',     label: 'Alarm Contacts',    icon: UserCheck },
  { divider: true, label: 'System' },
  { to: '/org/schedule-tasks',     label: 'Schedule Tasks',  icon: CalendarClock },
  { to: '/org/settings',           label: 'Settings',        icon: Settings },
]

export const userNav = [
  { divider: true, label: 'Main' },
  { to: '/user',                   label: 'Dashboard',          icon: LayoutDashboard },
  { to: '/user/custom-dashboard',  label: 'Custom Dashboards',  icon: LayoutTemplate },
  { divider: true, label: 'Account' },
  { to: '/user/subscription',      label: 'Subscription',       icon: CreditCard },
  { to: '/user/products',          label: 'Products',           icon: ShoppingBag },
  { divider: true, label: 'Device Data' },
  { to: '/user/schedule',          label: 'Schedule',           icon: Calendar },
  { to: '/user/slab-rates',        label: 'Slab Rates',         icon: Layers },
  { to: '/user/interval-history',  label: 'Interval History',   icon: Clock },
  { divider: true, label: 'Alarms' },
  { to: '/user/alarm-template',    label: 'Alarm Template',     icon: BellRing },
  { to: '/user/notifications',     label: 'Notifications',      icon: Bell },
  { divider: true, label: 'Analytics' },
  { to: '/user/ai-analytics',      label: 'AI Analytics',       icon: BrainCircuit },
  { to: '/user/voltage-imbalance', label: 'Voltage Imbalance',  icon: Gauge },
  { to: '/user/current-imbalance', label: 'Current Imbalance',  icon: Activity },
  { to: '/user/power-factor',      label: 'Power Factor',       icon: TrendingUp },
  { to: '/user/energy-consumption',label: 'Energy Consumption', icon: Zap },
  { to: '/user/anomalies',         label: 'Anomalies',          icon: AlertOctagon },
]
