"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _admin_dashboard from './admin-dashboard.bones.json'
import _org_dashboard from './org-dashboard.bones.json'
import _user_dashboard from './user-dashboard.bones.json'

registerBones({
  "admin-dashboard": _admin_dashboard,
  "org-dashboard": _org_dashboard,
  "user-dashboard": _user_dashboard,
})
