-- Fleet formula sync: legacy ControlFormula -> controlFormula
-- Generated by generate-sync-legacy-formulas.py

-- Fico Furnace slave THD reg 40330 cleared (legacy hides tab; was: =s/10)
UPDATE device_template_variables SET "controlFormula" = NULL, "acquisitionFormula" = NULL WHERE id = '0b980e69-9be3-4df1-8a22-ab8fd2c71f93';
-- Fico Furnace slave THD reg 40332 cleared (legacy hides tab; was: =s/10)
UPDATE device_template_variables SET "controlFormula" = NULL, "acquisitionFormula" = NULL WHERE id = 'e9b7dd94-5fff-40e0-80d9-bfa323edf5da';
-- Fico Furnace slave THD reg 40327 cleared (legacy hides tab; was: =s/10)
UPDATE device_template_variables SET "controlFormula" = NULL, "acquisitionFormula" = NULL WHERE id = '9b7db3d4-0001-4bd5-a5a8-42920ae21015';
-- Fico Furnace slave THD reg 40328 cleared (legacy hides tab; was: =s/10)
UPDATE device_template_variables SET "controlFormula" = NULL, "acquisitionFormula" = NULL WHERE id = '10716a5b-5546-4ab0-9688-d656f3a543fa';
-- Fico Furnace slave THD reg 40329 cleared (legacy hides tab; was: =s/10)
UPDATE device_template_variables SET "controlFormula" = NULL, "acquisitionFormula" = NULL WHERE id = '07d27c53-73b3-4337-aa0c-b7602d0b7833';
-- Fico Furnace slave THD reg 40331 cleared (legacy hides tab; was: =s/10)
UPDATE device_template_variables SET "controlFormula" = NULL, "acquisitionFormula" = NULL WHERE id = 'abcf501c-f602-4f28-aef0-8c3b94dab577';

-- Total template updates: 6
