-- Fleet-wide sync: legacy tblDeviceTemplateVariable ControlFormula -> controlFormula
-- Generated by sync script; only updates rows where formula differs.
-- Safe to re-run (idempotent).

BEGIN;

-- CF SMART TECHNOLOGIES MONITORING SYSTEM | AdminOfficeArea | reg 40107 | LineVoltageC
UPDATE device_template_variables SET "controlFormula" = '=s/10022' WHERE id = '6ae726b3-2612-4a60-a555-cf52489d4adc';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | AdminOfficeArea | reg 40128 | R40128
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '8aebb79d-d272-4358-bdd7-144ef05829f5';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | AdminOfficeArea | reg 40139 | Energy
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = 'eb3f56aa-ac92-4a65-b824-32726c4d57bb';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | CallibrationLab | reg 40084 | PowerFactor
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '08225ed5-9485-4445-a2a6-f68156ecdffa';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | CallibrationLab | reg 40085 | Frequency
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = '1517d5c6-b5fb-4597-adc7-0d8260d7fdb3';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | CallibrationLab | reg 40121 | ActivePower
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '52d6ae1e-1eb6-48dc-a851-453a9c76e43b';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | CallibrationLab | reg 40129 | ReactivePower
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = 'b1d84cfa-4e44-4902-8cfa-cedd95a1ea1d';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | CallibrationLab | reg 40137 | R40137
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '81e136f2-6671-44a9-b05f-3f7648186a70';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | CallibrationLab | reg 40327 | R40327
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = '0554c774-1f50-424b-b00c-ea386075c8d0';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | CallibrationLab | reg 40328 | R40328
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = '244cacc8-5735-4b09-8826-4bec3c8279d9';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | CallibrationLab | reg 40329 | R40329
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = 'd6b5b267-a470-4b81-a8de-7d2066037af1';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | CallibrationLab | reg 40330 | R40330
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = 'c4aae9fa-e9b3-4a5f-ac93-ef6f4fa96e75';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | CallibrationLab | reg 40331 | R40331
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = 'a07925a8-65d0-43b7-91aa-b866beb48aaf';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | CallibrationLab | reg 40332 | R40332
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = '7c35dea8-cafd-41ad-9b3f-6a42ccbb92f6';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | ExtendedLab | reg 40107 | LineVoltageC
UPDATE device_template_variables SET "controlFormula" = '=s/10022' WHERE id = 'cae558ca-64b4-4f76-b7e7-b36c9b7ca7bd';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | ExtendedLab | reg 40128 | R40128
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = 'e6b7c949-5dbd-4a1a-8e76-21df3fc63722';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | ExtendedLab | reg 40139 | Energy
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '1f2878a0-a9b5-4d22-b954-e1901f1fefb8';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | GeneratorFuel | reg 40001 | R40001
UPDATE device_template_variables SET "controlFormula" = '=s*0.9398*0.6096*1.03' WHERE id = '243aaa7b-0316-4f49-82e5-0baa936dd262';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | GeneratorFuel | reg 40004 | R40004
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = '49e0c87a-a4bb-4619-8543-58e526e8d878';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncomingCF | reg 40081 | PowerFactor
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '97d6a21f-d9c3-41d5-9f51-618447eb3084';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncomingCF | reg 40085 | Frequency
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = '202c023a-8e61-4150-a5ac-fa94cfc6bf9a';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncomingCF | reg 40327 | R40327
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = '72cf74b5-e994-4a93-b56b-5f963e1523b0';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncomingCF | reg 40328 | R40328
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = 'a4ca6b47-f292-482e-abae-6ef1ac75b89e';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncomingCF | reg 40329 | R40329
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = 'ce00f1c2-8203-4a48-8d0e-d48d62ff40b2';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncomingCF | reg 40330 | R40330
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = '7a864c4b-eeeb-4cdc-9605-70edbab22202';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncomingCF | reg 40331 | R40331
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = '08c758fb-aef6-492a-9f65-66e6ae79f125';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncomingCF | reg 40332 | R40332
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = 'c4fd381b-0a52-4aca-ad51-48c491e63bfc';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncoming | reg 40580 | R40580
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = 'b8eee2f5-9796-44eb-8f5c-bd239fa3ed4d';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncoming | reg 40581 | R40581
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = 'd870f7d0-9754-4ff6-9118-e540151ce45e';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncoming | reg 40582 | R40582
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = '35396a68-b049-45aa-8f89-5563c5ee8c7b';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncoming | reg 40583 | R40583
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = 'aab22444-d693-4449-8936-5dd6f44d4ae6';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncoming | reg 40584 | R40584
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = 'a5ad113c-7ed5-4613-8f9c-5e694e501f0a';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | MainIncoming | reg 40585 | R40585
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = 'bf5178e4-4300-43cf-8f51-92a9bc9b4ed4';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | ProductionArea | reg 40107 | LineVoltageC
UPDATE device_template_variables SET "controlFormula" = '=s/10022' WHERE id = '6ab3885b-9c95-4c94-a4d1-c1e2a4437306';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | ProductionArea | reg 40128 | R40128
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '951dcb7a-e656-426b-8ab4-47d2842665d7';
-- CF SMART TECHNOLOGIES MONITORING SYSTEM | ProductionArea | reg 40139 | Energy
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '859e0db8-21d8-43e5-8a91-1aecd4b2b112';
-- EMS PANEL | EMS PANEL | reg 40084 | PowerFactor
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '5996795d-ade9-4c39-bdcf-dcd6b7aacac4';
-- EMS PANEL | EMS PANEL | reg 40085 | Frequency
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = '72d35c01-7002-49ba-9eee-8399ec9bac5c';
-- EMS PANEL | EMS PANEL | reg 40109 | CurrentA
UPDATE device_template_variables SET "controlFormula" = '=s*10' WHERE id = '2d57f4af-2695-4923-a628-4c4368146d72';
-- EMS PANEL | EMS PANEL | reg 40121 | ActivePower
UPDATE device_template_variables SET "controlFormula" = '=s*10' WHERE id = '399c6e13-6b43-45ea-8c29-2b15c8d57117';
-- EMS PANEL | Sensor | reg 40033 | SensorA
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = '8bffd081-c045-4917-b594-269ba9a2f309';
-- EMS PANEL | Sensor | reg 40034 | R40034
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = '4d5e4482-f0b1-42bd-88d0-e4e2f3fcda31';
-- FICO EV | Charger | reg 40081 | PowerFactor
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '901f70da-b2e4-433e-8154-475ab7e5551f';
-- FICO EV | Charger | reg 40085 | Frequency
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = '21672314-8e79-45cc-80b2-b7ad439364b1';
-- FICO EV | FicoInverter | reg 40085 | Frequency
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = '5bb6d8c4-f063-4745-800d-eecd2be7cdac';
-- Fico Furnace | Fico Furnace | reg 40003 | Temperature
UPDATE device_template_variables SET "controlFormula" = '=s/10' WHERE id = 'd1221e7d-8a97-4d20-b22d-cf089f518ea5';
-- Fico Furnace | Fico Furnace | reg 40084 | PowerFactor
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = 'fb413169-2e17-4b3e-b468-c2b3e1f0e51c';
-- Fico Furnace | Fico Furnace | reg 40085 | Frequency
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = '5a0dbd8e-d46c-441a-bb79-c3671dff3961';
-- Fico Furnace | Fico Furnace | reg 40121 | ActivePower
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = 'fa3afcbf-6d1e-4551-88b3-8817dd8624ec';
-- Fico Furnace | Main | reg 40085 | Frequency
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = 'bda24a0d-9ffc-48c2-a9ab-c7b7b0a2875c';
-- Fico Furnace | Main | reg 40121 | ActivePower
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = 'a7d3f5c3-6154-4ed7-85d9-3503b2049efe';
-- Fico Furnace | Main | reg 40129 | ReactivePower
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '8ed33b50-c387-43ed-8824-29a54e70f6c8';
-- Fico Furnace | Main | reg 40137 | ApparentPower
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = 'be8debed-f619-4666-bf94-5473ce403e80';
-- Gulshan-e-Zia | MainBreaker | reg 40084 | PowerFactor
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = 'a5297187-556d-4c49-a8f5-cba508b15a51';
-- Gulshan-e-Zia | MainBreaker | reg 40085 | Frequency
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = '43f02131-700b-4468-b75a-d9b32cc92189';
-- JAPAN ELECTRONICS | Smart | reg 40097 | VoltageA
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = '565a7767-8501-44d4-ae96-3b282bbe8231';
-- JAPAN ELECTRONICS | Smart | reg 40099 | VoltageB
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = 'da5add1d-b87a-4aba-8d75-4f9f448a870e';
-- JAPAN ELECTRONICS | Smart | reg 40101 | VoltageC
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = 'e4d84d10-6650-4337-85c0-5bd9de68ae92';
-- JAPAN ELECTRONICS | Smart | reg 40109 | CurrentA
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = 'a4113980-d3c2-4a9c-9a5b-a4a99265704a';
-- JAPAN ELECTRONICS | Smart | reg 40111 | CurrentB
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = '50244188-ea0a-4ba1-8760-397fdb5ea8f6';
-- JAPAN ELECTRONICS | Smart | reg 40113 | CurrentC
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = '15bc2347-36df-4e4b-a318-37ee85ee2418';
-- JAPAN ELECTRONICS | Smart | reg 40107 | LineVoltageC
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = '51c49ae1-fd95-4d2b-a600-b62428a12c7c';
-- JAPAN ELECTRONICS | Smart | reg 40139 | Energy
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = 'a40ab3a0-f66e-44dc-a654-073ce27f3b5e';
-- JAPAN ELECTRONICS | Smart | reg 40141 | ExportPower
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = 'eeccd64d-d40f-41d9-a5c7-08af4e0c65de';
-- JAPAN ELECTRONICS | SmartLoad | reg 40067 | R40067
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = '107d7faa-3ef1-4c20-9496-08e6f018f00c';
-- JAPAN ELECTRONICS | SmartLoad | reg 40069 | R40069
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = 'f8734b4c-4773-4bfb-9e59-9e36612698b5';
-- JAPAN ELECTRONICS | SmartLoad | reg 40071 | R40071
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = 'b2673430-015b-4313-9e5c-74b39839e31f';
-- JAPAN ELECTRONICS | SmartLoad | reg 40089 | R40089
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = 'cf8c6613-30eb-4e9a-ba67-a81a40d0321b';
-- JAPAN ELECTRONICS | SmartLoad | reg 40091 | R40091
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = 'f07f79ce-5709-4174-af50-e44bb14a115f';
-- JAPAN ELECTRONICS | SmartLoad | reg 40093 | R40093
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = 'c274e504-942c-4972-8b27-00468cd226df';
-- JAPAN ELECTRONICS | SmartLoad | reg 40107 | LineVoltageC
UPDATE device_template_variables SET "controlFormula" = '=s/10000' WHERE id = '7c5ccb66-5fd8-4fde-85c5-c249ecfd5277';
-- JAPAN ELECTRONICS | SmartLoad | reg 40139 | Energy
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '48f9fde6-1dd4-4b9e-a078-f746b19ae9c5';
-- JAPAN ELECTRONICS | SmartLoad | reg 40141 | ExportPower
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '31363768-8333-4999-900f-50a32de0bd5f';
-- SUPRA STEEL FURNACE | SupraFurnace | reg 40084 | PowerFactor
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = 'e37db377-fcb6-43cb-be7f-57dd052dcc1d';
-- SUPRA STEEL FURNACE | SupraFurnace | reg 40085 | Frequency
UPDATE device_template_variables SET "controlFormula" = '=s/100' WHERE id = 'a6ba5952-877a-4857-b60d-0af8cd3a8a47';
-- SUPRA STEEL FURNACE | SupraFurnace | reg 40121 | ActivePower
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '0d1adad7-a5cf-4ce7-ae7a-9cc3fae29350';
-- SUPRA STEEL FURNACE | SupraFurnace | reg 40129 | ReactivePower
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = '2850b310-7346-4961-9b32-dee8c80b0af7';
-- SUPRA STEEL FURNACE | SupraFurnace | reg 40137 | R40137
UPDATE device_template_variables SET "controlFormula" = '=s/1000' WHERE id = 'ac14d9fd-8155-410c-ba0e-1597d48bf932';

-- Applied 78 formula updates
COMMIT;
